//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horizon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Horizon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap About_Thumb {
            get {
                object obj = ResourceManager.GetObject("About_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutLogo {
            get {
                object obj = ResourceManager.GetObject("AboutLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AC2_Thumb {
            get {
                object obj = ResourceManager.GetObject("AC2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AC3_Thumb {
            get {
                object obj = ResourceManager.GetObject("AC3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AC4_Thumb {
            get {
                object obj = ResourceManager.GetObject("AC4_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACBrotherhood_Thumb {
            get {
                object obj = ResourceManager.GetObject("ACBrotherhood_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Account_Thumb {
            get {
                object obj = ResourceManager.GetObject("Account_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACR_Thumb {
            get {
                object obj = ResourceManager.GetObject("ACR_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ACRogue_Thumb {
            get {
                object obj = ResourceManager.GetObject("ACRogue_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Adder_Thumb {
            get {
                object obj = ResourceManager.GetObject("Adder_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlanWake_Thumb {
            get {
                object obj = ResourceManager.GetObject("AlanWake_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignCenter {
            get {
                object obj = ResourceManager.GetObject("AlignCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignLeft {
            get {
                object obj = ResourceManager.GetObject("AlignLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignRight {
            get {
                object obj = ResourceManager.GetObject("AlignRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AvatarAward_Thumb {
            get {
                object obj = ResourceManager.GetObject("AvatarAward_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AvatarColorRectangle {
            get {
                object obj = ResourceManager.GetObject("AvatarColorRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AvatarEditor_Thumb {
            get {
                object obj = ResourceManager.GetObject("AvatarEditor_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AvP_Thumb {
            get {
                object obj = ResourceManager.GetObject("AvP_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bandage {
            get {
                object obj = ResourceManager.GetObject("Bandage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bastion_Thumb {
            get {
                object obj = ResourceManager.GetObject("Bastion_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Batman_Arkham_City_Thumb {
            get {
                object obj = ResourceManager.GetObject("Batman_Arkham_City_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BattleBlock_Theater_Thumb {
            get {
                object obj = ResourceManager.GetObject("BattleBlock_Theater_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bayonetta_Thumb {
            get {
                object obj = ResourceManager.GetObject("Bayonetta_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BBC2_Thumb {
            get {
                object obj = ResourceManager.GetObject("BBC2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bionic_Commando_Thumb {
            get {
                object obj = ResourceManager.GetObject("Bionic_Commando_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bioshock_2_Thumb {
            get {
                object obj = ResourceManager.GetObject("Bioshock_2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BioShock_Infinite_Thumb {
            get {
                object obj = ResourceManager.GetObject("BioShock_Infinite_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlackSkull {
            get {
                object obj = ResourceManager.GetObject("BlackSkull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blur_Thumb {
            get {
                object obj = ResourceManager.GetObject("Blur_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Borderlands_Thumb {
            get {
                object obj = ResourceManager.GetObject("Borderlands_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brink_Thumb {
            get {
                object obj = ResourceManager.GetObject("Brink_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrutalLegend_Thumb {
            get {
                object obj = ResourceManager.GetObject("BrutalLegend_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bulletstorm_Thumb {
            get {
                object obj = ResourceManager.GetObject("Bulletstorm_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captcha_Diamond {
            get {
                object obj = ResourceManager.GetObject("Captcha_Diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CC_Thumb {
            get {
                object obj = ResourceManager.GetObject("CC_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CoDAdvancedWarfare_Thumb {
            get {
                object obj = ResourceManager.GetObject("CoDAdvancedWarfare_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CodeVeronicaX_Thumb {
            get {
                object obj = ResourceManager.GetObject("CodeVeronicaX_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CoDGhostsThumb {
            get {
                object obj = ResourceManager.GetObject("CoDGhostsThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Console {
            get {
                object obj = ResourceManager.GetObject("Console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crackdown_Thumb {
            get {
                object obj = ResourceManager.GetObject("Crackdown_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crackdown2_Thumb {
            get {
                object obj = ResourceManager.GetObject("Crackdown2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown1 {
            get {
                object obj = ResourceManager.GetObject("Crown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown10 {
            get {
                object obj = ResourceManager.GetObject("Crown10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown2 {
            get {
                object obj = ResourceManager.GetObject("Crown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown3 {
            get {
                object obj = ResourceManager.GetObject("Crown3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown4 {
            get {
                object obj = ResourceManager.GetObject("Crown4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown5 {
            get {
                object obj = ResourceManager.GetObject("Crown5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown6 {
            get {
                object obj = ResourceManager.GetObject("Crown6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown7 {
            get {
                object obj = ResourceManager.GetObject("Crown7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown8 {
            get {
                object obj = ResourceManager.GetObject("Crown8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crown9 {
            get {
                object obj = ResourceManager.GetObject("Crown9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crysis2_Thumb {
            get {
                object obj = ResourceManager.GetObject("Crysis2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crysis3_Thumb {
            get {
                object obj = ResourceManager.GetObject("Crysis3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Darksiders_Thumb {
            get {
                object obj = ResourceManager.GetObject("Darksiders_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeadIsland_Thumb {
            get {
                object obj = ResourceManager.GetObject("DeadIsland_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeadRising2_Thumb {
            get {
                object obj = ResourceManager.GetObject("DeadRising2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceExplorer_Thumb {
            get {
                object obj = ResourceManager.GetObject("DeviceExplorer_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevilMayCry3_Thumb {
            get {
                object obj = ResourceManager.GetObject("DevilMayCry3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevilMayCry4_Thumb {
            get {
                object obj = ResourceManager.GetObject("DevilMayCry4_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevilMayCry5_Thumb {
            get {
                object obj = ResourceManager.GetObject("DevilMayCry5_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiRT2_Thumb {
            get {
                object obj = ResourceManager.GetObject("DiRT2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiRT3_Thumb {
            get {
                object obj = ResourceManager.GetObject("DiRT3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiRTShowdown_Thumb {
            get {
                object obj = ResourceManager.GetObject("DiRTShowdown_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DragonBallXenoVerse_Thumb {
            get {
                object obj = ResourceManager.GetObject("DragonBallXenoVerse_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DragonsDogma_Thumb {
            get {
                object obj = ResourceManager.GetObject("DragonsDogma_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DS_Thumb {
            get {
                object obj = ResourceManager.GetObject("DS_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DS2_Thumb {
            get {
                object obj = ResourceManager.GetObject("DS2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DS3_Thumb {
            get {
                object obj = ResourceManager.GetObject("DS3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EarnedAchievement {
            get {
                object obj = ResourceManager.GetObject("EarnedAchievement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EarnedAvatarAward {
            get {
                object obj = ResourceManager.GetObject("EarnedAvatarAward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Enslaved_Odyssey_Thumb {
            get {
                object obj = ResourceManager.GetObject("Enslaved_Odyssey_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fable2_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Fable2_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FarCry3_Thumb {
            get {
                object obj = ResourceManager.GetObject("FarCry3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FarCry3BloodDragon_Thumb {
            get {
                object obj = ResourceManager.GetObject("FarCry3BloodDragon_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FarCry4_Thumb {
            get {
                object obj = ResourceManager.GetObject("FarCry4_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FatxHDD_24 {
            get {
                object obj = ResourceManager.GetObject("FatxHDD_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FatxMU_24 {
            get {
                object obj = ResourceManager.GetObject("FatxMU_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FatxUSB_24 {
            get {
                object obj = ResourceManager.GetObject("FatxUSB_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FEAR_2_Thumb {
            get {
                object obj = ResourceManager.GetObject("FEAR_2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FEAR_Thumb {
            get {
                object obj = ResourceManager.GetObject("FEAR_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIFA11_Thumb {
            get {
                object obj = ResourceManager.GetObject("FIFA11_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIFA12_Thumb {
            get {
                object obj = ResourceManager.GetObject("FIFA12_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIFA13_Thumb {
            get {
                object obj = ResourceManager.GetObject("FIFA13_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIFA14_Thumb {
            get {
                object obj = ResourceManager.GetObject("FIFA14_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FIFA15_Thumb {
            get {
                object obj = ResourceManager.GetObject("FIFA15_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileIcon {
            get {
                object obj = ResourceManager.GetObject("FileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindTID_Thumb {
            get {
                object obj = ResourceManager.GetObject("FindTID_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flame {
            get {
                object obj = ResourceManager.GetObject("Flame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flame_Small {
            get {
                object obj = ResourceManager.GetObject("Flame_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forza3_SS_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Forza3_SS_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forza3_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Forza3_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forza4_Livery_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Forza4_Livery_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forza4_SS_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Forza4_SS_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forza4_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Forza4_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForzaHorizon_Livery_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("ForzaHorizon_Livery_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForzaHorizon_SS_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("ForzaHorizon_SS_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForzaHorizon_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("ForzaHorizon_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForzaHorizon2_FnF_Thumb {
            get {
                object obj = ResourceManager.GetObject("ForzaHorizon2_FnF_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForzaHorizon2_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("ForzaHorizon2_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GamercardViewer_Thumb {
            get {
                object obj = ResourceManager.GetObject("GamercardViewer_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GamerPictureManager_Thumb {
            get {
                object obj = ResourceManager.GetObject("GamerPictureManager_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gamerscore {
            get {
                object obj = ResourceManager.GetObject("Gamerscore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoW_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoW_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoW2_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoW2_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoW3_Profile_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoW3_Profile_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoW3_Stats_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoW3_Stats_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoW3_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoW3_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoWJ_Stats_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoWJ_Stats_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoWJ_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("GoWJ_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrayDot {
            get {
                object obj = ResourceManager.GetObject("GrayDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenDot {
            get {
                object obj = ResourceManager.GetObject("GreenDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_AA12 {
            get {
                object obj = ResourceManager.GetObject("GTA4_AA12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Advanced_MG {
            get {
                object obj = ResourceManager.GetObject("GTA4_Advanced_MG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_AdvancedSniper {
            get {
                object obj = ResourceManager.GetObject("GTA4_AdvancedSniper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_AK47 {
            get {
                object obj = ResourceManager.GetObject("GTA4_AK47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Assault_Shotgun {
            get {
                object obj = ResourceManager.GetObject("GTA4_Assault_Shotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Automatic_9mm {
            get {
                object obj = ResourceManager.GetObject("GTA4_Automatic_9mm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_BaseballBat {
            get {
                object obj = ResourceManager.GetObject("GTA4_BaseballBat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_CombatShotgun {
            get {
                object obj = ResourceManager.GetObject("GTA4_CombatShotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_CombatSniper {
            get {
                object obj = ResourceManager.GetObject("GTA4_CombatSniper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_DesertEagle {
            get {
                object obj = ResourceManager.GetObject("GTA4_DesertEagle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Fist {
            get {
                object obj = ResourceManager.GetObject("GTA4_Fist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Glock {
            get {
                object obj = ResourceManager.GetObject("GTA4_Glock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_GoldUzi {
            get {
                object obj = ResourceManager.GetObject("GTA4_GoldUzi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Grenade {
            get {
                object obj = ResourceManager.GetObject("GTA4_Grenade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Grenade_Launcher {
            get {
                object obj = ResourceManager.GetObject("GTA4_Grenade_Launcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Knife {
            get {
                object obj = ResourceManager.GetObject("GTA4_Knife", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_M4Carbine {
            get {
                object obj = ResourceManager.GetObject("GTA4_M4Carbine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_MicroUZI {
            get {
                object obj = ResourceManager.GetObject("GTA4_MicroUZI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Molotov {
            get {
                object obj = ResourceManager.GetObject("GTA4_Molotov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_MP5 {
            get {
                object obj = ResourceManager.GetObject("GTA4_MP5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_P90 {
            get {
                object obj = ResourceManager.GetObject("GTA4_P90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Pipe_Bomb {
            get {
                object obj = ResourceManager.GetObject("GTA4_Pipe_Bomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Pistol44 {
            get {
                object obj = ResourceManager.GetObject("GTA4_Pistol44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Pool_Cue {
            get {
                object obj = ResourceManager.GetObject("GTA4_Pool_Cue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_PumpShotgun {
            get {
                object obj = ResourceManager.GetObject("GTA4_PumpShotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_RPG {
            get {
                object obj = ResourceManager.GetObject("GTA4_RPG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_Sawed_Off_Shotgun {
            get {
                object obj = ResourceManager.GetObject("GTA4_Sawed_Off_Shotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_SniperRifle {
            get {
                object obj = ResourceManager.GetObject("GTA4_SniperRifle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA4_StickyBomb {
            get {
                object obj = ResourceManager.GetObject("GTA4_StickyBomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTAIV_Thumb {
            get {
                object obj = ResourceManager.GetObject("GTAIV_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTAV_Thumb {
            get {
                object obj = ResourceManager.GetObject("GTAV_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo3_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Halo3_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo3ODST_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Halo3ODST_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_0 {
            get {
                object obj = ResourceManager.GetObject("Halo4_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_1 {
            get {
                object obj = ResourceManager.GetObject("Halo4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_10 {
            get {
                object obj = ResourceManager.GetObject("Halo4_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_11 {
            get {
                object obj = ResourceManager.GetObject("Halo4_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_12 {
            get {
                object obj = ResourceManager.GetObject("Halo4_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_13 {
            get {
                object obj = ResourceManager.GetObject("Halo4_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_14 {
            get {
                object obj = ResourceManager.GetObject("Halo4_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_2 {
            get {
                object obj = ResourceManager.GetObject("Halo4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_3 {
            get {
                object obj = ResourceManager.GetObject("Halo4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_4 {
            get {
                object obj = ResourceManager.GetObject("Halo4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_5 {
            get {
                object obj = ResourceManager.GetObject("Halo4_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_6 {
            get {
                object obj = ResourceManager.GetObject("Halo4_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_7 {
            get {
                object obj = ResourceManager.GetObject("Halo4_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_8 {
            get {
                object obj = ResourceManager.GetObject("Halo4_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_9 {
            get {
                object obj = ResourceManager.GetObject("Halo4_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_Megalo_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Halo4_Megalo_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halo4_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("Halo4_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HaloReach_Megalo_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("HaloReach_Megalo_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HaloReach_Thumb_New {
            get {
                object obj = ResourceManager.GetObject("HaloReach_Thumb_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InjusticeGAU_Thumb {
            get {
                object obj = ResourceManager.GetObject("InjusticeGAU_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Just_Cause_Thumb {
            get {
                object obj = ResourceManager.GetObject("Just_Cause_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap L4D2_Thumb {
            get {
                object obj = ResourceManager.GetObject("L4D2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LIMBO_Thumb {
            get {
                object obj = ResourceManager.GetObject("LIMBO_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoadingLogo {
            get {
                object obj = ResourceManager.GetObject("LoadingLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo64 {
            get {
                object obj = ResourceManager.GetObject("Logo64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LostOdyssey_Thumb {
            get {
                object obj = ResourceManager.GetObject("LostOdyssey_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Manager_Thumb {
            get {
                object obj = ResourceManager.GetObject("Manager_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarbleBlastUltra_Thumb {
            get {
                object obj = ResourceManager.GetObject("MarbleBlastUltra_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaxPayne3_Thumb {
            get {
                object obj = ResourceManager.GetObject("MaxPayne3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeatBoy {
            get {
                object obj = ResourceManager.GetObject("MeatBoy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Medal_Blue {
            get {
                object obj = ResourceManager.GetObject("Medal_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MercuryHg_Thumb {
            get {
                object obj = ResourceManager.GetObject("MercuryHg_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Metro_2033_Thumb {
            get {
                object obj = ResourceManager.GetObject("Metro_2033_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Milestone1 {
            get {
                object obj = ResourceManager.GetObject("Milestone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MLB_2k13_Thumb {
            get {
                object obj = ResourceManager.GetObject("MLB_2k13_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoH_Thumb {
            get {
                object obj = ResourceManager.GetObject("MoH_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MotocrossMadness_Thumb {
            get {
                object obj = ResourceManager.GetObject("MotocrossMadness_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MW3_Thumb {
            get {
                object obj = ResourceManager.GetObject("MW3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NarutoStorm2_Thumb {
            get {
                object obj = ResourceManager.GetObject("NarutoStorm2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NarutoStorm3_Thumb {
            get {
                object obj = ResourceManager.GetObject("NarutoStorm3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NaughtyBear_Thumb {
            get {
                object obj = ResourceManager.GetObject("NaughtyBear_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NBA_2K13Thumb {
            get {
                object obj = ResourceManager.GetObject("NBA_2K13Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NBA_2K14Thumb {
            get {
                object obj = ResourceManager.GetObject("NBA_2K14Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NBA_2K15_Thumb {
            get {
                object obj = ResourceManager.GetObject("NBA_2K15_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeedForSpeedHP_Thumb {
            get {
                object obj = ResourceManager.GetObject("NeedForSpeedHP_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NPlus_Thumb {
            get {
                object obj = ResourceManager.GetObject("NPlus_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Oblivion_Thumb {
            get {
                object obj = ResourceManager.GetObject("Oblivion_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Page {
            get {
                object obj = ResourceManager.GetObject("Page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageWarning {
            get {
                object obj = ResourceManager.GetObject("PageWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Partition {
            get {
                object obj = ResourceManager.GetObject("Partition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pencil {
            get {
                object obj = ResourceManager.GetObject("Pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PGR4_Thumb {
            get {
                object obj = ResourceManager.GetObject("PGR4_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlantsVsZombies_Thumb {
            get {
                object obj = ResourceManager.GetObject("PlantsVsZombies_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Profile_Thumb {
            get {
                object obj = ResourceManager.GetObject("Profile_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProfileEditor_Thumb {
            get {
                object obj = ResourceManager.GetObject("ProfileEditor_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prototype_Thumb {
            get {
                object obj = ResourceManager.GetObject("Prototype_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuakeArenaArcade_Thumb {
            get {
                object obj = ResourceManager.GetObject("QuakeArenaArcade_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuestionMark {
            get {
                object obj = ResourceManager.GetObject("QuestionMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuestionMarkWide {
            get {
                object obj = ResourceManager.GetObject("QuestionMarkWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RE5_Thumb {
            get {
                object obj = ResourceManager.GetObject("RE5_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RE6_Thumb {
            get {
                object obj = ResourceManager.GetObject("RE6_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedDead_Thumb {
            get {
                object obj = ResourceManager.GetObject("RedDead_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedDot {
            get {
                object obj = ResourceManager.GetObject("RedDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedFaction_Thumb {
            get {
                object obj = ResourceManager.GetObject("RedFaction_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedFlag {
            get {
                object obj = ResourceManager.GetObject("RedFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap REORC_Thumb {
            get {
                object obj = ResourceManager.GetObject("REORC_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Saboteur_Thumb {
            get {
                object obj = ResourceManager.GetObject("Saboteur_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaintsRow3_Thumb {
            get {
                object obj = ResourceManager.GetObject("SaintsRow3_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaintsRow4_Thumb {
            get {
                object obj = ResourceManager.GetObject("SaintsRow4_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaintsRowGOOH_Thumb {
            get {
                object obj = ResourceManager.GetObject("SaintsRowGOOH_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveIcon {
            get {
                object obj = ResourceManager.GetObject("SaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Skyrim_Thumb {
            get {
                object obj = ResourceManager.GetObject("Skyrim_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingDogs_Thumb {
            get {
                object obj = ResourceManager.GetObject("SleepingDogs_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SMB_Thumb {
            get {
                object obj = ResourceManager.GetObject("SMB_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Smile {
            get {
                object obj = ResourceManager.GetObject("Smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic_Thumb {
            get {
                object obj = ResourceManager.GetObject("Sonic_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SSXTricky_Thumb {
            get {
                object obj = ResourceManager.GetObject("SSXTricky_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarWarsTFUII_Thumb {
            get {
                object obj = ResourceManager.GetObject("StarWarsTFUII_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StateOfDecay_Thumb {
            get {
                object obj = ResourceManager.GetObject("StateOfDecay_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Swarm_Thumb {
            get {
                object obj = ResourceManager.GetObject("Swarm_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TestDrive_Thumb {
            get {
                object obj = ResourceManager.GetObject("TestDrive_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TestDrive2_Thumb {
            get {
                object obj = ResourceManager.GetObject("TestDrive2_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theme_Game {
            get {
                object obj = ResourceManager.GetObject("Theme_Game", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theme_Main {
            get {
                object obj = ResourceManager.GetObject("Theme_Main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theme_Other {
            get {
                object obj = ResourceManager.GetObject("Theme_Other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Theme_Thumb {
            get {
                object obj = ResourceManager.GetObject("Theme_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TigerWoods14_Thumb {
            get {
                object obj = ResourceManager.GetObject("TigerWoods14_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tile {
            get {
                object obj = ResourceManager.GetObject("Tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TitleIdFinder_Default {
            get {
                object obj = ResourceManager.GetObject("TitleIdFinder_Default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TombRaider_Thumb {
            get {
                object obj = ResourceManager.GetObject("TombRaider_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transparent_32 {
            get {
                object obj = ResourceManager.GetObject("Transparent_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Trash {
            get {
                object obj = ResourceManager.GetObject("Trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Trophy {
            get {
                object obj = ResourceManager.GetObject("Trophy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unearned {
            get {
                object obj = ResourceManager.GetObject("Unearned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unlocker_Thumb {
            get {
                object obj = ResourceManager.GetObject("Unlocker_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpArrowSilver {
            get {
                object obj = ResourceManager.GetObject("UpArrowSilver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UserSingle {
            get {
                object obj = ResourceManager.GetObject("UserSingle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VisitUs_Thumb {
            get {
                object obj = ResourceManager.GetObject("VisitUs_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WarpZone {
            get {
                object obj = ResourceManager.GetObject("WarpZone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatchDogs_Thumb {
            get {
                object obj = ResourceManager.GetObject("WatchDogs_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WET_Thumb {
            get {
                object obj = ResourceManager.GetObject("WET_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YuGiOh_5DS_Thumb {
            get {
                object obj = ResourceManager.GetObject("YuGiOh_5DS_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YuGiOh_MD_Thumb {
            get {
                object obj = ResourceManager.GetObject("YuGiOh_MD_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
